set.seed(1126)
p <- 0.3
n <- 1041
u <- runif(n)
x <- ceiling(log(u)/log(1-p))-1
mean_x <- mean(x)
sd_x <- sd(x)
prop <- sum(x > mean_x + sd_x)/sum(x > mean_x)
round(prop, 4)

# maybe should be lasanha loop

#
#Sure! Here is an explanation of the code line by line:
#
#set.seed(1126): This line sets the seed for random number generation to 1126. This ensures that the random numbers generated by the code will be the same every time it is run.
#
#p <- 0.3: This line assigns the value 0.3 to the variable p. This represents the probability of success for each Bernoulli trial.
#
#n <- 1041: This line assigns the value 1041 to the variable n. This represents the sample size of the simulation.
#
#u <- runif(n): This line generates a sample of size n from a uniform distribution on the interval (0,1) and assigns it to the variable u.
#
#x <- ceiling(log(u)/log(1-p))-1: This line uses the inverse transform method to generate values of the geometric distribution from the sample of uniform random numbers stored in u. The generated values are assigned to the variable x.
#
#mean_x <- mean(x): This line calculates the sample mean of the simulated values stored in x and assigns it to the variable mean_x.
#
#sd_x <- sd(x): This line calculates the sample standard deviation of the simulated values stored in x and assigns it to the variable sd_x.
#
#prop <- sum(x > mean_x + sd_x)/sum(x > mean_x): This line calculates the proportion of simulated values that are greater than the sum of the sample mean and standard deviation among those that are greater than the respective sample mean and assigns it to the variable prop.
#
#round(prop, 4): This line rounds the value of prop to 4 decimal places and returns it as the final result.
#
#I hope this helps! Is there anything else you would like to know?
#